<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Delete, Edit, Key, Plus, Refresh, Search } from '@element-plus/icons-vue'
import { managementApi, type Permission, type Role, type User } from '../api'
import { usePaged } from '../composables/usePaged'
import { useAction } from '../composables/useAction'
import { useAuth } from '../stores/auth'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
import ScopeEditor from '../components/ScopeEditor.vue'
const auth = useAuth(), { busy, run, confirm } = useAction(), tab = ref(auth.can('user.read') ? 'users' : 'roles')
const users = usePaged(managementApi.users, undefined, ['access.changed'], () => auth.can('user.read'))
const roles = ref<Role[]>([]), permissions = ref<Permission[]>([])
const userDialog = ref(false), roleDialog = ref(false), permissionDialog = ref(false), editingUser = ref<number | null>(null), editingRole = ref<number | null>(null)
const scope = ref<{ target: 'user' | 'role'; id: number; name: string }>()
const userForm = reactive({ username: '', password: '', displayName: '', phone: '', status: 'active', roleIds: [] as number[] })
const roleForm = reactive({ name: '', code: '', status: 'active', permissionCodes: [] as string[] })
const permissionRole = ref<Role>(), codes = ref<string[]>([])
async function loadRoles() { if (auth.can('role.read')) roles.value = await managementApi.roles() }
async function loadOptions() { await run(async () => { await loadRoles(); if (auth.can('role.manage')) permissions.value = await managementApi.permissions() }, '') }
function editUser(user?: User) { editingUser.value = user?.id || null; Object.assign(userForm, { username: user?.username || '', password: '', displayName: user?.displayName || '', phone: user?.phone || '', status: user?.status || 'active', roleIds: [...(user?.roleIds || [])] }); userDialog.value = true }
function editRole(role?: Role) { editingRole.value = role?.id || null; Object.assign(roleForm, { name: role?.name || '', code: role?.code || '', status: role?.status || 'active', permissionCodes: [...(role?.permissionCodes || [])] }); roleDialog.value = true }
async function saveUser() { if (await run(async () => { if (!userForm.username.trim()) throw new Error('请输入账号'); if (!editingUser.value && !userForm.password) throw new Error('新增账号必须设置密码'); await managementApi.saveUser(editingUser.value, { ...userForm, username: userForm.username.trim(), password: userForm.password || undefined }); await users.load(); await loadRoles() }, '账号已保存')) { userDialog.value = false; userForm.password = '' } }
async function saveRole() { if (await run(async () => { if (!roleForm.name.trim() || !roleForm.code.trim()) throw new Error('请填写角色名称和编码'); await managementApi.saveRole(editingRole.value, { ...roleForm, name: roleForm.name.trim(), code: roleForm.code.trim() }); await loadRoles() }, '角色已保存')) roleDialog.value = false }
async function removeRole(role: Role) { await confirm(`删除角色“${role.name}”？`, async () => { await managementApi.deleteRole(role.id); await loadRoles() }, '角色已删除') }
async function savePermissions() { if (!permissionRole.value) return; if (await run(async () => { await managementApi.rolePermissions(permissionRole.value!.id, codes.value); await loadRoles() }, '功能权限已保存')) permissionDialog.value = false }
function editPermissions(role: Role) { permissionRole.value = role; codes.value = [...role.permissionCodes]; permissionDialog.value = true }
onMounted(loadOptions)
</script>
<template><div><PageHeader title="账号与角色"><el-button :icon="Refresh" @click="users.load(); loadOptions()">刷新</el-button><el-button v-if="tab === 'users' && auth.can('user.manage')" type="primary" :icon="Plus" @click="editUser()">新增账号</el-button><el-button v-if="tab === 'roles' && auth.can('role.manage')" type="primary" :icon="Plus" @click="editRole()">新增角色</el-button></PageHeader><el-tabs v-model="tab"><el-tab-pane v-if="auth.can('user.read')" label="账号" name="users" /><el-tab-pane v-if="auth.can('role.read') || auth.can('role.manage')" label="角色与权限" name="roles" /></el-tabs><template v-if="tab === 'users'"><form class="filter-bar" @submit.prevent="users.load(true)"><el-input v-model="users.search.value" clearable :prefix-icon="Search" placeholder="账号、姓名或手机号" aria-label="搜索账号" @clear="users.load(true)" /><el-button :icon="Search" native-type="submit">查询</el-button></form><el-alert v-if="users.error.value" :title="users.error.value" type="error" :closable="false" /><el-table v-loading="users.loading.value" :data="users.items.value" row-key="id" empty-text="暂无账号"><el-table-column prop="username" label="账号" min-width="130" /><el-table-column prop="displayName" label="姓名" min-width="130" /><el-table-column prop="phone" label="手机号码" min-width="140" /><el-table-column label="角色" min-width="200"><template #default="{ row }"><div class="tag-list"><el-tag v-for="id in row.roleIds" :key="id" type="info" size="small">{{ roles.find(role => role.id === id)?.name || `角色 ${id}` }}</el-tag><span v-if="!row.roleIds.length" class="muted">未分配</span></div></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><StatusBadge :value="row.status" /></template></el-table-column><el-table-column v-if="auth.can('user.manage')" label="操作" width="154" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="scope = { target: 'user', id: row.id, name: row.username }">数据范围</el-button><el-tooltip content="编辑账号"><el-button text :icon="Edit" aria-label="编辑账号" @click="editUser(row as User)" /></el-tooltip></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="users.page.value" v-model:page-size="users.pageSize.value" :total="users.total.value" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @current-change="users.load()" @size-change="users.load(true)" /></div></template>
<el-table v-else :data="roles" row-key="id" empty-text="暂无角色"><el-table-column prop="name" label="角色名称" min-width="150" /><el-table-column prop="code" label="编码" min-width="150" /><el-table-column prop="userCount" label="账号数" width="90" /><el-table-column label="功能权限" width="100"><template #default="{ row }">{{ row.permissionCodes.length }} 项</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><StatusBadge :value="row.status" /></template></el-table-column><el-table-column v-if="auth.can('role.manage')" label="操作" width="260" fixed="right"><template #default="{ row }"><el-button link type="primary" :icon="Key" @click="editPermissions(row as Role)">功能权限</el-button><el-button link type="primary" @click="scope = { target: 'role', id: row.id, name: row.name }">数据范围</el-button><el-button text :icon="Edit" aria-label="编辑角色" @click="editRole(row as Role)" /><el-button text type="danger" :icon="Delete" :disabled="busy" aria-label="删除角色" @click="removeRole(row as Role)" /></template></el-table-column></el-table>
<el-dialog v-model="userDialog" :title="editingUser ? '编辑账号' : '新增账号'" width="560px" destroy-on-close @closed="userForm.password = ''"><el-form label-position="top"><div class="form-grid"><el-form-item label="账号" required><el-input v-model="userForm.username" maxlength="80" autocomplete="off" /></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.displayName" maxlength="80" /></el-form-item><el-form-item label="手机号码"><el-input v-model="userForm.phone" maxlength="30" /></el-form-item><el-form-item :label="editingUser ? '新密码（留空保留原密码）' : '密码'" :required="!editingUser"><el-input v-model="userForm.password" type="password" show-password autocomplete="new-password" maxlength="256" /></el-form-item></div><el-form-item label="角色"><el-select v-model="userForm.roleIds" multiple filterable><el-option v-for="role in roles" :key="role.id" :label="role.name" :value="role.id" :disabled="role.status !== 'active'" /></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="userForm.status"><el-radio-button value="active">启用</el-radio-button><el-radio-button value="disabled">停用</el-radio-button><el-radio-button value="locked">锁定</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="userDialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="saveUser">保存</el-button></template></el-dialog>
<el-dialog v-model="roleDialog" :title="editingRole ? '编辑角色' : '新增角色'" width="440px"><el-form label-position="top"><el-form-item label="角色名称" required><el-input v-model="roleForm.name" maxlength="80" /></el-form-item><el-form-item label="角色编码" required><el-input v-model="roleForm.code" maxlength="64" /></el-form-item><el-form-item label="状态"><el-switch v-model="roleForm.status" active-value="active" inactive-value="disabled" active-text="启用" /></el-form-item></el-form><template #footer><el-button @click="roleDialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="saveRole">保存</el-button></template></el-dialog>
<el-dialog v-model="permissionDialog" :title="`功能权限 · ${permissionRole?.name || ''}`" width="660px"><el-checkbox-group v-model="codes" class="permission-grid"><el-checkbox v-for="permission in permissions" :key="permission.code" :value="permission.code">{{ permission.name }}</el-checkbox></el-checkbox-group><template #footer><el-button @click="permissionDialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="savePermissions">保存权限</el-button></template></el-dialog><ScopeEditor v-if="scope" :target="scope.target" :target-id="scope.id" :name="scope.name" @close="scope = undefined" /></div></template>
