<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { ArrowDown, ArrowUp, Delete, Edit, Plus, Refresh, StarFilled, VideoPlay } from '@element-plus/icons-vue'
import { allPages, managementApi, mediaApi, type Channel, type Layout } from '../api'
import { useAction } from '../composables/useAction'
import { useEvents } from '../stores/events'
import { useAuth } from '../stores/auth'
import { errorMessage } from '../lib/format'
import { layoutSlots, patrolChannels } from '../lib/layouts'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
const auth = useAuth(), { busy, run, confirm } = useAction(), layouts = ref<Layout[]>([]), channels = ref<Channel[]>([]), favorites = ref<Channel[]>([]), error = ref(''), loading = ref(false), dialog = ref(false), editing = ref<number | null>(null), selectedChannel = ref<number>()
const form = reactive<Omit<Layout, 'id'>>({ name: '', kind: 'layout', shared: false, layout: 4, intervalSeconds: 30, channelIds: [null, null, null, null] })
const available = computed(() => channels.value.filter(channel => !form.channelIds.includes(channel.id)))
const canShare = computed(() => auth.can('layout.share'))
async function load() { loading.value = true; error.value = ''; try { const data = await Promise.all([mediaApi.layouts(), mediaApi.favorites(), allPages(managementApi.channels)]); layouts.value = data[0]; favorites.value = data[1]; channels.value = data[2] } catch (e) { error.value = errorMessage(e) } finally { loading.value = false } }
function edit(layout?: Layout) { editing.value = layout?.id || null; Object.assign(form, { name: layout?.name || '', kind: layout?.kind || 'layout', shared: layout?.shared || false, layout: layout?.layout || 4, intervalSeconds: layout?.intervalSeconds || 30 }); form.channelIds = form.kind === 'layout' ? layoutSlots(layout?.channelIds || [], form.layout) : patrolChannels(layout?.channelIds || []); selectedChannel.value = undefined; dialog.value = true }
function addChannel() { if (selectedChannel.value && !form.channelIds.includes(selectedChannel.value)) { form.channelIds.push(selectedChannel.value); selectedChannel.value = undefined } }
function move(index: number, direction: number) { const other = index + direction; if (other >= 0 && other < form.channelIds.length) [form.channelIds[index], form.channelIds[other]] = [form.channelIds[other], form.channelIds[index]] }
async function save() { if (await run(async () => { if (!form.name.trim()) throw new Error('请输入方案名称'); if (form.kind === 'patrol' && !patrolChannels(form.channelIds).length) throw new Error('轮巡至少添加一路通道'); if (!Number.isInteger(form.intervalSeconds) || form.intervalSeconds < 10 || form.intervalSeconds > 300) throw new Error('轮巡间隔应为 10～300 秒'); await mediaApi.saveLayout(editing.value, { ...form, channelIds: form.kind === 'layout' ? layoutSlots(form.channelIds, form.layout) : patrolChannels(form.channelIds), name: form.name.trim(), shared: canShare.value && form.shared }); await load() }, '方案已保存')) dialog.value = false }
watch(() => form.layout, () => { if (form.kind === 'layout') form.channelIds = layoutSlots(form.channelIds, form.layout) }, { flush: 'sync' })
watch(() => form.kind, kind => { form.channelIds = kind === 'layout' ? layoutSlots(form.channelIds, form.layout) : patrolChannels(form.channelIds) }, { flush: 'sync' })
async function remove(layout: Layout) { await confirm(`删除方案“${layout.name}”？`, async () => { await mediaApi.deleteLayout(layout.id); await load() }, '方案已删除') }
async function unfavorite(channel: Channel) { await run(async () => { await mediaApi.saveFavorites(favorites.value.filter(item => item.id !== channel.id).map(item => item.id)); favorites.value = await mediaApi.favorites() }, '已取消收藏') }
const unsubscribe = useEvents().subscribe(['access.changed', 'device.changed', 'reconnected'], load)
onMounted(load); onBeforeUnmount(unsubscribe)
</script>
<template><div><PageHeader title="收藏与轮巡"><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="edit()">新建方案</el-button></PageHeader><el-alert v-if="error" :title="error" type="error" :closable="false" /><section class="page-section"><div class="section-heading"><h2>个人收藏</h2><span class="muted">{{ favorites.length }} 路通道</span></div><el-empty v-if="!favorites.length" description="暂无收藏通道" :image-size="64" /><div v-else class="favorites-list"><div v-for="channel in favorites" :key="channel.id" class="favorite-item"><div><strong>{{ channel.alias || channel.name }}</strong><small>{{ channel.deviceName }} · 通道 {{ channel.deviceChannel }}</small></div><StatusBadge :value="channel.status" /><router-link :to="{ path: '/app/live', query: { channelId: channel.id } }"><el-button text :icon="VideoPlay" aria-label="预览收藏通道" /></router-link><el-tooltip content="取消收藏"><el-button text :icon="StarFilled" :disabled="busy" aria-label="取消收藏" @click="unfavorite(channel)" /></el-tooltip></div></div></section><section class="page-section"><div class="section-heading"><h2>布局与轮巡方案</h2><span class="muted">{{ layouts.length }} 个方案</span></div><el-table v-loading="loading" :data="layouts" empty-text="暂无布局或轮巡方案"><el-table-column prop="name" label="名称" min-width="150" /><el-table-column label="类型" width="90"><template #default="{ row }">{{ row.kind === 'patrol' ? '轮巡' : '布局' }}</template></el-table-column><el-table-column label="可见范围" width="100"><template #default="{ row }">{{ row.shared ? '共享' : '个人' }}</template></el-table-column><el-table-column label="窗口" width="90"><template #default="{ row }">{{ row.layout }} 分屏</template></el-table-column><el-table-column label="通道" width="90"><template #default="{ row }">{{ patrolChannels(row.channelIds).length }} 路</template></el-table-column><el-table-column label="停留时间" width="100"><template #default="{ row }">{{ row.kind === 'patrol' ? `${row.intervalSeconds} 秒` : '—' }}</template></el-table-column><el-table-column label="操作" width="174" fixed="right"><template #default="{ row }"><div class="table-tools"><router-link :to="{ path: '/app/live', query: { layoutId: row.id } }"><el-button link type="primary" :icon="VideoPlay">打开</el-button></router-link><template v-if="!row.shared || canShare"><el-button text :icon="Edit" aria-label="编辑方案" @click="edit(row as Layout)" /><el-button text type="danger" :icon="Delete" :disabled="busy" aria-label="删除方案" @click="remove(row as Layout)" /></template></div></template></el-table-column></el-table></section>
<el-dialog v-model="dialog" :title="editing ? '编辑方案' : '新建方案'" width="640px" destroy-on-close><el-form label-position="top"><div class="form-grid"><el-form-item label="方案名称" required><el-input v-model="form.name" maxlength="100" /></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.kind"><el-radio-button value="layout">布局</el-radio-button><el-radio-button value="patrol">轮巡</el-radio-button></el-radio-group></el-form-item><el-form-item label="窗口数量"><el-segmented v-model="form.layout" :options="[1, 4, 9, 16]" /></el-form-item><el-form-item v-if="form.kind === 'patrol'" label="停留时间（秒）"><el-input-number v-model="form.intervalSeconds" :min="10" :max="300" :precision="0" /></el-form-item><el-form-item v-if="canShare" label="共享方案"><el-switch v-model="form.shared" /></el-form-item></div><div v-if="form.kind === 'layout'" class="form-grid"><el-form-item v-for="(_, index) in form.channelIds" :key="index" :label="`窗口 ${index + 1}`"><el-select :model-value="form.channelIds[index]" clearable filterable placeholder="空窗口" :aria-label="`窗口 ${index + 1} 通道`" @update:model-value="value => form.channelIds[index] = typeof value === 'number' ? value : null"><el-option v-for="channel in channels" :key="channel.id" :value="channel.id" :label="`${channel.deviceName} / ${channel.alias || channel.name}`" /></el-select></el-form-item></div><template v-else><el-form-item label="通道顺序" required><div class="channel-order-picker"><el-select v-model="selectedChannel" filterable placeholder="选择通道"><el-option v-for="channel in available" :key="channel.id" :value="channel.id" :label="`${channel.deviceName} / ${channel.alias || channel.name}`" /></el-select><el-button :icon="Plus" :disabled="!selectedChannel" aria-label="添加通道" @click="addChannel" /></div></el-form-item><ol class="channel-order-list"><li v-for="(id, index) in form.channelIds" :key="index"><span>{{ index + 1 }}. {{ channels.find(channel => channel.id === id)?.alias || channels.find(channel => channel.id === id)?.name || `不可访问通道 ${id}` }}</span><el-button text :icon="ArrowUp" :disabled="index === 0" aria-label="上移通道" @click="move(index, -1)" /><el-button text :icon="ArrowDown" :disabled="index === form.channelIds.length - 1" aria-label="下移通道" @click="move(index, 1)" /><el-button text type="danger" :icon="Delete" aria-label="移除通道" @click="form.channelIds.splice(index, 1)" /></li></ol></template></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存方案</el-button></template></el-dialog></div></template>
