<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { Delete, Edit, Plus, Refresh, Search } from '@element-plus/icons-vue'
import { allPages, managementApi, type Channel, type Device, type Organization, type OrganizationKind, type OrganizationNode } from '../api'
import { usePaged } from '../composables/usePaged'
import { useAction } from '../composables/useAction'
import { useAuth } from '../stores/auth'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
const route = useRoute(), auth = useAuth(), { busy, run, confirm } = useAction()
const organization = ref<Organization>({ workshops: [], areas: [], units: [] }), devices = ref<Device[]>([])
const deviceId = ref<number | undefined>(Number(route.query.deviceId) || undefined), unitId = ref<number>(), online = ref<string>('')
const { items, total, page, pageSize, search, loading, error, load } = usePaged(managementApi.channels, () => ({ deviceId: deviceId.value, unitId: unitId.value, online: online.value }), ['device.changed', 'access.changed'])
const selected = ref<Channel[]>([]), assignTo = ref<number | null>(null), assignmentOpen = ref(false), nodeDialog = ref(false), editing = ref<number | null>(null)
const kind = ref<OrganizationKind>('workshops'), orgTab = ref<OrganizationKind>('workshops')
const names: Record<OrganizationKind, string> = { workshops: '车间', areas: '区域', units: '单元' }
const form = reactive({ name: '', code: '', status: 'active', parentId: null as number | null })
const parents = computed(() => kind.value === 'areas' ? organization.value.workshops : kind.value === 'units' ? organization.value.areas : [])
async function loadOrganization() { organization.value = await managementApi.organization() }
async function loadOptions() { await run(async () => { await loadOrganization(); if (auth.can('device.read')) devices.value = await allPages(managementApi.devices) }, '') }
function editNode(node?: OrganizationNode) { kind.value = orgTab.value; editing.value = node?.id || null; Object.assign(form, { name: node?.name || '', code: node?.code || '', status: node?.status || 'active', parentId: node?.parentId ?? null }); nodeDialog.value = true }
async function saveNode() { if (await run(async () => { if (!form.name.trim() || !form.code.trim()) throw new Error('请填写名称和编码'); if (kind.value !== 'workshops' && !form.parentId) throw new Error('请选择上级组织'); await managementApi.saveNode(kind.value, editing.value, { ...form, name: form.name.trim(), code: form.code.trim(), parentId: kind.value === 'workshops' ? null : form.parentId }); await loadOrganization() }, '组织已保存')) nodeDialog.value = false }
async function removeNode(node: OrganizationNode) { await confirm(`删除${names[orgTab.value]}“${node.name}”？`, async () => { await managementApi.deleteNode(orgTab.value, node.id); await loadOrganization(); await load() }, '组织已删除') }
async function assign() { if (await run(async () => { await managementApi.assign(selected.value.map(channel => channel.id), assignTo.value ?? null); await load() }, '通道分配已更新')) { assignmentOpen.value = false; selected.value = [] } }
function parentName(node: OrganizationNode) { return [...organization.value.workshops, ...organization.value.areas].find(parent => parent.id === node.parentId)?.name || '—' }
onMounted(loadOptions)
</script>
<template><div><PageHeader title="组织与通道" :count="total"><el-button :icon="Refresh" :loading="loading" @click="loadOptions(); load()">刷新</el-button></PageHeader><div class="organization-workspace"><aside class="organization-pane"><div class="section-heading"><h2>业务组织</h2><el-tooltip content="新增组织"><el-button v-if="auth.can('area.manage')" text :icon="Plus" aria-label="新增组织" @click="editNode()" /></el-tooltip></div><el-tabs v-model="orgTab"><el-tab-pane v-for="(name, key) in names" :key="key" :name="key" :label="name" /></el-tabs><div v-if="!organization[orgTab].length" class="compact-empty">暂无{{ names[orgTab] }}</div><div v-for="node in organization[orgTab]" :key="node.id" class="organization-row"><div><strong>{{ node.name }}</strong><small>{{ node.code }}<template v-if="node.parentId"> · {{ parentName(node) }}</template></small></div><div v-if="auth.can('area.manage')" class="table-tools"><el-button text :icon="Edit" aria-label="编辑组织" @click="editNode(node)" /><el-button text type="danger" :icon="Delete" :disabled="busy" aria-label="删除组织" @click="removeNode(node)" /></div></div></aside>
<section class="channel-table-pane"><form class="filter-bar" @submit.prevent="load(true)"><el-input v-model="search" clearable :prefix-icon="Search" placeholder="搜索通道" aria-label="搜索通道" @clear="load(true)" /><el-select v-if="devices.length" v-model="deviceId" clearable placeholder="全部设备" aria-label="设备筛选" @change="load(true)"><el-option v-for="device in devices" :key="device.id" :value="device.id" :label="device.name" /></el-select><el-select v-model="unitId" clearable placeholder="全部单元" aria-label="单元筛选" @change="load(true)"><el-option v-for="unit in organization.units" :key="unit.id" :value="unit.id" :label="unit.name" /></el-select><el-select v-model="online" clearable placeholder="全部状态" aria-label="在线状态筛选" @change="load(true)"><el-option label="在线" value="true" /><el-option label="离线" value="false" /></el-select><el-button native-type="submit" :icon="Search">查询</el-button></form><div v-if="auth.can('channel.assign')" class="selection-bar"><span>已选 {{ selected.length }} 路通道</span><el-button :disabled="!selected.length" @click="assignTo = null; assignmentOpen = true">批量分配</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon /><el-table v-loading="loading" :data="items" row-key="id" empty-text="暂无通道" @selection-change="selected = $event"><el-table-column v-if="auth.can('channel.assign')" type="selection" width="44" /><el-table-column prop="name" label="通道" min-width="140" show-overflow-tooltip /><el-table-column prop="deviceName" label="所属设备" min-width="135" /><el-table-column prop="deviceChannel" label="设备内通道" width="104" /><el-table-column label="状态" width="90"><template #default="{ row }"><StatusBadge :value="row.status" /></template></el-table-column><el-table-column label="所属单元" min-width="120"><template #default="{ row }">{{ organization.units.find(unit => unit.id === row.unitId)?.name || '未分配' }}</template></el-table-column><el-table-column prop="codec" label="编码" width="90" /><el-table-column label="云台" width="72"><template #default="{ row }">{{ row.ptzCapable ? '支持' : '—' }}</template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @current-change="load()" @size-change="load(true)" /></div></section></div>
<el-dialog v-model="nodeDialog" :title="`${editing ? '编辑' : '新增'}${names[kind]}`" width="460px" destroy-on-close><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="form.name" maxlength="100" /></el-form-item><el-form-item label="编码" required><el-input v-model="form.code" maxlength="64" /></el-form-item><el-form-item v-if="kind !== 'workshops'" label="上级组织" required><el-select v-model="form.parentId" filterable><el-option v-for="parent in parents" :key="parent.id" :value="parent.id" :label="parent.name" /></el-select></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" active-value="active" inactive-value="disabled" active-text="启用" /></el-form-item></el-form><template #footer><el-button @click="nodeDialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="saveNode">保存</el-button></template></el-dialog>
<el-dialog v-model="assignmentOpen" title="批量分配通道" width="420px"><el-form label-position="top"><el-form-item label="目标单元"><el-select v-model="assignTo" clearable filterable placeholder="不选择单元则解除分配"><el-option v-for="unit in organization.units" :key="unit.id" :value="unit.id" :label="unit.name" /></el-select></el-form-item></el-form><p class="muted">已选 {{ selected.length }} 路通道</p><template #footer><el-button @click="assignmentOpen = false">取消</el-button><el-button type="primary" :loading="busy" @click="assign">确认分配</el-button></template></el-dialog></div></template>
