<script setup lang="ts">
import { reactive, ref } from 'vue'
import { Download, Plus, Refresh, Upload } from '@element-plus/icons-vue'
import { workflowApi, type Release } from '../api'
import { bytes, dateTime } from '../lib/format'
import { usePaged } from '../composables/usePaged'
import { useAction } from '../composables/useAction'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
const { busy, run, confirm } = useAction(), dialog = ref(false), publishDialog = ref(false), selected = ref<Release>(), file = ref<File>()
const form = reactive({ version: '', releaseNotes: '', minimumVersion: '', forceUpdate: false }), publishForm = reactive({ minimumVersion: '', forceUpdate: false })
const { items, total, page, pageSize, loading, error, load } = usePaged(workflowApi.releases)
function pick(event: Event) { file.value = (event.target as HTMLInputElement).files?.[0] }
function openUpload() { Object.assign(form, { version: '', releaseNotes: '', minimumVersion: '', forceUpdate: false }); file.value = undefined; dialog.value = true }
function validVersion(value: string) { return /^\d+\.\d+\.\d+(?:\.\d+)?$/.test(value) }
async function upload() { if (await run(async () => { if (!file.value) throw new Error('请选择安装包'); if (!/\.(msi|zip)$/i.test(file.value.name)) throw new Error('请选择 MSI 安装包或 ZIP 便携包'); if (!validVersion(form.version.trim())) throw new Error('请输入有效版本号，例如 2.0.0'); if (form.minimumVersion && !validVersion(form.minimumVersion.trim())) throw new Error('最低版本号格式无效'); const data = new FormData(); data.append('file', file.value); data.append('version', form.version.trim()); data.append('releaseNotes', form.releaseNotes); data.append('minimumVersion', form.minimumVersion.trim()); data.append('forceUpdate', String(form.forceUpdate)); await workflowApi.uploadRelease(data); await load(true) }, '安装包已上传为草稿')) dialog.value = false }
function openPublish(release: Release) { selected.value = release; Object.assign(publishForm, { minimumVersion: release.minimumVersion || '', forceUpdate: release.forceUpdate }); publishDialog.value = true }
async function publish() { if (!selected.value) return; if (await run(async () => { if (publishForm.minimumVersion && !validVersion(publishForm.minimumVersion.trim())) throw new Error('最低版本号格式无效'); await workflowApi.publish(selected.value!.id, publishForm.minimumVersion.trim(), publishForm.forceUpdate); await load() }, '版本已发布')) publishDialog.value = false }
async function revoke(release: Release) { await confirm(`撤回版本 ${release.version}？该版本将不再作为客户端下载版本。`, async () => { await workflowApi.revokeRelease(release.id); await load() }, '版本已撤回') }
</script>
<template><div><PageHeader title="版本发布" :count="total"><el-button :icon="Refresh" :loading="loading" @click="load()">刷新</el-button><el-button type="primary" :icon="Plus" @click="openUpload">上传安装包</el-button></PageHeader><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-table v-loading="loading" :data="items" empty-text="暂无客户端版本"><el-table-column type="expand"><template #default="{ row }"><div class="expanded-release"><h3>更新说明</h3><p class="preserve-lines">{{ row.releaseNotes || '未提供更新说明' }}</p><dl class="data-list"><div><dt>文件</dt><dd>{{ row.fileName }}</dd></div><div><dt>SHA-256</dt><dd class="hash">{{ row.sha256 }}</dd></div></dl></div></template></el-table-column><el-table-column prop="version" label="版本" min-width="110" /><el-table-column label="状态" width="110"><template #default="{ row }"><StatusBadge :value="row.status" /></template></el-table-column><el-table-column label="大小" width="110"><template #default="{ row }">{{ bytes(row.fileSize) }}</template></el-table-column><el-table-column prop="minimumVersion" label="最低版本" min-width="100" /><el-table-column label="强制更新" width="100"><template #default="{ row }">{{ row.forceUpdate ? '是' : '否' }}</template></el-table-column><el-table-column prop="downloadCount" label="下载次数" width="100" /><el-table-column label="发布时间" min-width="168"><template #default="{ row }">{{ dateTime(row.publishedAt) }}</template></el-table-column><el-table-column label="操作" width="178" fixed="right"><template #default="{ row }"><div class="table-tools"><el-button v-if="row.status !== 'published'" link type="primary" :disabled="busy" @click="openPublish(row as Release)">发布</el-button><el-button v-else link type="danger" :disabled="busy" @click="revoke(row as Release)">撤回</el-button><el-tooltip content="下载安装包"><a :href="workflowApi.releaseUrl(row.id)" class="icon-link" aria-label="下载安装包"><el-icon><Download /></el-icon></a></el-tooltip></div></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @current-change="load()" @size-change="load(true)" /></div>
<el-dialog v-model="dialog" title="上传客户端安装包" width="580px" destroy-on-close :close-on-click-modal="!busy" :show-close="!busy"><el-form label-position="top"><el-form-item label="安装文件（MSI 或 ZIP）" required><input class="file-input" type="file" accept=".msi,.zip" :disabled="busy" aria-label="安装文件" @change="pick" /><span v-if="file" class="muted">{{ bytes(file.size) }}</span></el-form-item><div class="form-grid"><el-form-item label="版本号" required><el-input v-model="form.version" placeholder="2.0.0" /></el-form-item><el-form-item label="最低支持版本"><el-input v-model="form.minimumVersion" placeholder="2.0.0" /></el-form-item></div><el-form-item label="更新说明"><el-input v-model="form.releaseNotes" type="textarea" :rows="5" maxlength="4096" /></el-form-item><el-form-item label="强制更新"><el-switch v-model="form.forceUpdate" /></el-form-item></el-form><template #footer><el-button :disabled="busy" @click="dialog = false">取消</el-button><el-button type="primary" :icon="Upload" :loading="busy" @click="upload">上传为草稿</el-button></template></el-dialog>
<el-dialog v-model="publishDialog" :title="`发布版本 ${selected?.version || ''}`" width="460px"><el-form label-position="top"><el-form-item label="最低支持版本"><el-input v-model="publishForm.minimumVersion" /></el-form-item><el-form-item label="强制更新"><el-switch v-model="publishForm.forceUpdate" /></el-form-item></el-form><template #footer><el-button @click="publishDialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="publish">确认发布</el-button></template></el-dialog></div></template>
