<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VideoPlatform.Domain/VideoPlatform.Domain.csproj" />
    <ProjectReference Include="../VideoPlatform.Contracts/VideoPlatform.Contracts.csproj" />
  </ItemGroup>
</Project>
