<script setup lang="ts">
import { ref, watch } from 'vue'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Close, FullScreen, Plus, Minus, Refresh, ZoomIn, ZoomOut } from '@element-plus/icons-vue'
import { mediaApi, type Channel, type PtzCommand } from '../api'
import { usePtz } from '../composables/usePtz'
import { useAction } from '../composables/useAction'
const props = defineProps<{ channel?: Channel; allowed: boolean }>()
const ptz = usePtz(), { busy, run } = useAction(), speed = ref(4), preset = ref(1)
const operations = [{ command: 'zoomIn', name: '放大', icon: ZoomIn }, { command: 'zoomOut', name: '缩小', icon: ZoomOut }, { command: 'focusNear', name: '近焦', icon: Plus }, { command: 'focusFar', name: '远焦', icon: Minus }, { command: 'irisOpen', name: '开大光圈', icon: FullScreen }, { command: 'irisClose', name: '缩小光圈', icon: Close }] as const
function start(command: PtzCommand, event?: PointerEvent) { if (props.channel && props.allowed && props.channel.ptzCapable) { if (event) (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); void ptz.start(props.channel.id, command, speed.value) } }
async function goPreset() { if (props.channel) await run(() => mediaApi.preset(props.channel!.id, preset.value), '预置位已调用') }
watch(() => props.channel?.id, () => void ptz.stop())
watch(() => props.allowed, allowed => { if (!allowed) void ptz.stop() })
</script>
<template><section class="ptz-panel"><div class="section-heading"><h2>云台控制</h2><span class="muted">{{ channel?.ptzCapable ? channel.name : '当前通道不支持' }}</span></div><fieldset :disabled="!allowed || !channel?.ptzCapable"><div class="ptz-pad"><el-tooltip content="向上"><button class="ptz-up" aria-label="向上" @pointerdown.prevent="start('up', $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start('up')" @keyup.space="ptz.stop()"><el-icon><ArrowUp /></el-icon></button></el-tooltip><el-tooltip content="向左"><button class="ptz-left" aria-label="向左" @pointerdown.prevent="start('left', $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start('left')" @keyup.space="ptz.stop()"><el-icon><ArrowLeft /></el-icon></button></el-tooltip><el-tooltip content="停止"><button class="ptz-center" aria-label="停止云台" @click="ptz.stop()"><el-icon><Close /></el-icon></button></el-tooltip><el-tooltip content="向右"><button class="ptz-right" aria-label="向右" @pointerdown.prevent="start('right', $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start('right')" @keyup.space="ptz.stop()"><el-icon><ArrowRight /></el-icon></button></el-tooltip><el-tooltip content="向下"><button class="ptz-down" aria-label="向下" @pointerdown.prevent="start('down', $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start('down')" @keyup.space="ptz.stop()"><el-icon><ArrowDown /></el-icon></button></el-tooltip></div><div class="ptz-extra"><el-tooltip content="自动扫描"><button aria-label="自动扫描" @pointerdown.prevent="start('auto', $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start('auto')" @keyup.space="ptz.stop()"><el-icon><Refresh /></el-icon></button></el-tooltip><el-tooltip v-for="operation in operations" :key="operation.command" :content="operation.name"><button :aria-label="operation.name" @pointerdown.prevent="start(operation.command, $event)" @pointerup="ptz.stop()" @keydown.space.prevent="start(operation.command)" @keyup.space="ptz.stop()"><el-icon><component :is="operation.icon" /></el-icon></button></el-tooltip></div><label class="ptz-speed">速度<el-slider v-model="speed" :min="1" :max="7" :step="1" show-stops aria-label="云台速度" /></label><div class="preset-control"><el-input-number v-model="preset" :min="1" :max="255" :precision="0" controls-position="right" aria-label="预置位编号" /><el-button :loading="busy" :disabled="!allowed || !channel?.ptzCapable" @click="goPreset">调用预置位</el-button></div></fieldset><small v-if="ptz.error.value" class="field-error">{{ ptz.error.value }}</small></section></template>
