<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/VideoPlatform.Desktop/VideoPlatform.Desktop.csproj" />
    <ProjectReference Include="../../src/VideoPlatform.Updater/VideoPlatform.Updater.csproj" />
    <ProjectReference Include="../../src/VideoPlatform.Api/VideoPlatform.Api.csproj" />
    <ProjectReference Include="../../src/Hikvision.Adapter/Hikvision.Adapter.csproj" />
  </ItemGroup>
</Project>
