internal static class EdgeNodeConfigurationPageV2
{
    public const string Html = """
<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VisiCore 边缘节点</title>
<style>
:root{color-scheme:light;font-family:Inter,"Microsoft YaHei UI",system-ui,sans-serif;color:#17212b;background:#eef2f5}*{box-sizing:border-box}body{max-width:1120px;margin:0 auto;padding:24px}header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin:4px 0 20px}h1{font-size:24px;margin:0}h2{font-size:15px;margin:0}p{margin:6px 0;color:#607080;font-size:13px}.state{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:650}.dot{width:10px;height:10px;border-radius:50%;background:#8d99a5}.dot.good{background:#17803d}.dot.warn{background:#b7791f}.dot.bad{background:#c23838}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.panel{background:#fff;border:1px solid #d9e0e6;border-radius:8px;padding:16px;box-shadow:0 1px 1px #182c3b0a}.metric{min-height:98px}.metric small,.label{display:block;color:#6a7884;font-size:12px}.metric strong{display:block;margin-top:8px;font-size:20px;line-height:1.15}.metric span{display:block;margin-top:5px;font-size:12px;color:#607080}.layout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.85fr);gap:16px;margin-top:16px}.stack{display:grid;gap:16px}.section-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}label{display:block;font-size:13px;font-weight:600}input,textarea{width:100%;margin-top:6px;border:1px solid #b9c6d0;border-radius:5px;padding:9px;font:inherit;background:#fff}input:disabled{background:#f1f4f6;color:#7c8994}textarea{resize:vertical}.toggle{display:flex;gap:8px;align-items:center;font-weight:500}.toggle input{width:auto;margin:0}button{appearance:none;border:0;border-radius:5px;background:#176b48;color:#fff;padding:9px 13px;font:inherit;font-size:13px;font-weight:600;cursor:pointer}button.secondary{background:#e8eef1;color:#283947}button:disabled{opacity:.55;cursor:not-allowed}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.notice{margin-top:12px;padding:10px 12px;border-left:3px solid #3c778f;background:#f4f8fa;color:#526572;font-size:12px;line-height:1.55}.notice.warn{border-color:#c88719;background:#fffaed}.status-line{font-size:13px;color:#3e5260;min-height:20px;margin-top:12px}.full{grid-column:1/-1}@media(max-width:760px){body{padding:14px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.layout{grid-template-columns:1fr}.fields{grid-template-columns:1fr}header{display:block}.state{margin-top:12px}}@media(max-width:420px){.grid{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>VisiCore 边缘节点</h1><p>本机运行与受控资源配置</p></div><div class="state"><i id="nodeDot" class="dot"></i><span id="nodeState">正在读取状态</span></div></header>
<section class="grid"><div class="panel metric"><small>节点状态</small><strong id="runtimeState">—</strong><span id="runtimeDetail">等待本地运行时</span></div><div class="panel metric"><small>中心连接</small><strong id="centerState">—</strong><span id="centerDetail">—</span></div><div class="panel metric"><small>CPU 使用率</small><strong id="cpuUsage">—</strong><span id="cpuLimit">未设置限制</span></div><div class="panel metric"><small>内存使用</small><strong id="memoryUsage">—</strong><span id="memoryLimit">未设置限制</span></div></section>
<main class="layout"><div class="stack"><section class="panel"><div class="section-title"><h2>连接与配对</h2><span class="label">一次性凭证只用于登记</span></div><div class="fields"><label>中心 HTTPS 地址<input id="center" placeholder="https://visicore.example.com/"></label><label>一次性配对凭证<input id="code" type="password" autocomplete="off"></label></div><div class="actions"><button class="secondary" onclick="testCenter()">测试连接</button><button onclick="applyConfig()">确认配对并生效</button></div><div id="connectionStatus" class="status-line"></div></section>
<section class="panel"><div class="section-title"><h2>资源策略</h2><span id="policyState" class="label">等待 Host Agent</span></div><div class="fields"><label class="toggle full"><input id="cpuEnabled" type="checkbox" onchange="togglePolicy()">限制 CPU 使用率</label><label>CPU 上限（宿主总算力 %）<input id="cpuLimitInput" type="number" min="1" max="100" value="50" disabled></label><label class="toggle full"><input id="memoryEnabled" type="checkbox" onchange="togglePolicy()">限制内存使用</label><label>内存上限（MiB）<input id="memoryLimitInput" type="number" min="256" max="4194304" value="1024" disabled></label><label>磁盘预警阈值（%）<input id="diskWarning" type="number" min="70" max="95" value="85"></label></div><div class="notice warn">保存后立即应用：Linux 会短暂重建边缘容器；Windows 会动态更新运行时限制。</div><div class="actions"><button class="secondary" id="testPolicyButton" onclick="testPolicy()">校验策略</button><button id="applyPolicyButton" onclick="applyPolicy()">保存并立即应用</button></div><div id="policyStatus" class="status-line"></div></section></div>
<aside class="stack"><section class="panel"><div class="section-title"><h2>运行详情</h2><button class="secondary" onclick="refreshStatus()">刷新</button></div><div class="fields"><div><span class="label">状态目录</span><strong id="diskUsage">—</strong><p id="diskDetail">—</p></div><div><span class="label">Host Agent</span><strong id="hostState">—</strong><p id="hostDetail">—</p></div><div class="full"><span class="label">最后更新</span><strong id="updatedAt">—</strong></div></div></section>
<section class="panel"><div class="section-title"><h2>Host Agent 与升级</h2></div><label class="toggle"><input id="hostEnabled" type="checkbox" checked>启用 Host Agent</label><label class="toggle"><input id="allowExecution" type="checkbox">允许受控升级</label><label>发行签名 PEM 文件<input id="pem" type="file" accept=".pem,text/plain"></label><label>公钥标识<input id="keyId" placeholder="release-key-2026"></label><label>受信下载域名<textarea id="hosts" rows="3">github.com
objects.githubusercontent.com</textarea></label><div class="actions"><button class="secondary" onclick="testHost()">校验 Host 设置</button></div><div id="hostStatus" class="status-line"></div></section></aside></main>
<script>
const $=id=>document.getElementById(id);let pemText='';$('pem').onchange=async e=>{pemText=e.target.files[0]?await e.target.files[0].text():''};const bytes=n=>{if(!Number.isFinite(n)||n<=0)return'未上报';let u=['B','KiB','MiB','GiB','TiB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};const time=v=>v?new Date(v).toLocaleString():'—';const stateLabel=s=>({running:'在线运行',awaiting_enrollment:'等待配对',starting:'正在启动',degraded:'运行异常',applied:'已生效',unlimited:'未限制',applying:'正在应用',failed:'应用失败',awaiting_agent:'等待 Agent',not_configured:'未配置'}[s]||s||'未上报');
function togglePolicy(){$('cpuLimitInput').disabled=!$('cpuEnabled').checked;$('memoryLimitInput').disabled=!$('memoryEnabled').checked}function policy(){return{cpuLimitPercent:$('cpuEnabled').checked?Number($('cpuLimitInput').value):null,memoryLimitMiB:$('memoryEnabled').checked?Number($('memoryLimitInput').value):null,diskWarningPercent:Number($('diskWarning').value)}}function host(){return{enabled:$('hostEnabled').checked,allowExecution:$('allowExecution').checked,signingPublicKeyId:$('keyId').value,signingPublicKeyPem:pemText,allowedArtifactHosts:$('hosts').value.split(/\n/),maximumArtifactBytes:2147483648,executionTimeoutSeconds:600,resourcePolicy:policy()}}function body(withCode=false){return{controlPlaneBaseUri:$('center').value,enrollmentCode:withCode?$('code').value:null,host:host()}}async function call(url,p){let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.failureKind||j.title||'请求失败');return j}
async function testCenter(){try{await call('/api/test',body());$('connectionStatus').textContent='中心 HTTPS 连接正常。'}catch(e){$('connectionStatus').textContent='连接测试失败：'+e.message}}async function testHost(){try{await call('/api/host-test',body());$('hostStatus').textContent='Host 设置校验通过。'}catch(e){$('hostStatus').textContent='Host 设置不可用：'+e.message}}async function applyConfig(){try{let r=await call('/api/apply',body(true));$('connectionStatus').textContent=r.hostRestarting?'配置已应用，Host Agent 正在重启。':'配置已应用，节点正在登记。';setTimeout(refreshStatus,3000)}catch(e){$('connectionStatus').textContent='配置未生效：'+e.message}}async function testPolicy(){try{await call('/api/resource-policy/test',{resourcePolicy:policy()});$('policyStatus').textContent='资源策略校验通过。'}catch(e){$('policyStatus').textContent='策略不可用：'+e.message}}async function applyPolicy(){try{let r=await call('/api/resource-policy/apply',{resourcePolicy:policy()});$('policyStatus').textContent=r.hostRestarting?'策略已保存，Linux Host Agent 正在重启。':'策略已立即生效。';setTimeout(refreshStatus,3000)}catch(e){$('policyStatus').textContent='策略未生效：'+e.message}}
function render(status){let runtime=status.runtime?.runtime||{},resource=runtime.resource||status.resource,online=!!status.available&&runtime.status==='running';$('nodeDot').className='dot '+(online?'good':runtime.status==='degraded'?'bad':'warn');$('nodeState').textContent=online?'节点在线':stateLabel(runtime.status);$('runtimeState').textContent=stateLabel(runtime.status);$('runtimeDetail').textContent=runtime.lastFailureKind?'失败：'+runtime.lastFailureKind:(status.agentVersion?'版本 '+status.agentVersion:'等待登记');$('centerState').textContent=status.isEnrolled?'已登记':'未登记';$('centerDetail').textContent=status.agentId?'节点 '+status.agentId.slice(0,8):'等待一次性配对';$('hostState').textContent=status.hostAgentAvailable?'可用':'未安装';$('hostDetail').textContent=status.hostAgentAvailable?'可执行受控资源策略':'资源限制不可生效';$('policyState').textContent=resource?stateLabel(resource.enforcementStatus):'未上报';$('updatedAt').textContent=time(resource?.sampledAt||runtime.updatedAt);if(resource){$('cpuUsage').textContent=resource.processCpuPercent?.toFixed(1)+'%';$('cpuLimit').textContent=resource.policy?.cpuLimitPercent?`上限 ${resource.policy.cpuLimitPercent}%`:'未设置限制';$('memoryUsage').textContent=bytes(resource.processMemoryBytes);$('memoryLimit').textContent=resource.policy?.memoryLimitMiB?`上限 ${resource.policy.memoryLimitMiB} MiB`:'未设置限制';$('diskUsage').textContent=bytes(resource.stateDirectoryTotalBytes-resource.stateDirectoryAvailableBytes)+' / '+bytes(resource.stateDirectoryTotalBytes);$('diskDetail').textContent=resource.diskWarning?'磁盘使用已达到预警阈值':`剩余 ${bytes(resource.stateDirectoryAvailableBytes)}`;let p=resource.policy||{};$('cpuEnabled').checked=!!p.cpuLimitPercent;$('memoryEnabled').checked=!!p.memoryLimitMiB;if(p.cpuLimitPercent)$('cpuLimitInput').value=p.cpuLimitPercent;if(p.memoryLimitMiB)$('memoryLimitInput').value=p.memoryLimitMiB;if(p.diskWarningPercent)$('diskWarning').value=p.diskWarningPercent;togglePolicy();$('policyStatus').textContent=resource.enforcementFailureKind?'执行失败：'+resource.enforcementFailureKind:''}let disabled=!status.hostAgentAvailable;$('testPolicyButton').disabled=disabled;$('applyPolicyButton').disabled=disabled}
async function refreshStatus(){try{let r=await fetch('/api/status'),j=await r.json();render(j)}catch{$('nodeState').textContent='本地运行时不可用'}}refreshStatus();setInterval(refreshStatus,5000);
</script></body></html>
""";
}
